Repository kyma-incubator/compass-console, pull requests merged in 2021-09, with the labels that each got.

#42 Rename master to main in makefiles
  Makefile
  components/react/Makefile
Labels: lgtm, size/XS

#44 Bump dependencies versions
  common/src/services/nest.tsx
  compass/package-lock.json
  compass/package.json
  compass/src/components/ApiPackages/CreateApiPackageForm/CreateApiPackageForm.js
  compass/src/components/Application/ApplicationDetails/ConnectApplicationModal/test/ConnectApplicationModal.test.js
  compass/src/components/Applications/CreateApplicationModal/CreateApplicationModal.component.js
  compass/src/components/MetadataDefinitions/gql.js
  compass/src/components/Runtimes/InfiniteList.js
  compass/src/components/Runtimes/RuntimeDetails/RuntimeScenarios/RuntimeScenarios.component.js
  compass/src/components/Scenarios/ScenarioDetails/ScenarioDetailsHeader/ScenarioDetailsHeader.js
  components/generic-documentation/package-lock.json
  components/generic-documentation/package.json
  components/generic-documentation/src/index.tsx
  components/generic-documentation/src/layouts/InstancesUI.tsx
  components/generic-documentation/src/render-engines/markdown/headers-toc/HeadersComponent.tsx
  components/generic-documentation/src/render-engines/markdown/helpers/checkIsInView.ts
  components/generic-documentation/src/render-engines/markdown/index.ts
  components/generic-documentation/src/render-engines/markdown/plugins/disableInternalLinks/index.ts
  components/generic-documentation/src/render-engines/open-api/components/SchemesWrapper.tsx
  components/generic-documentation/src/render-engines/open-api/plugins.tsx
  components/react/package-lock.json
  components/react/package.json
  components/shared/src/Notification/Notification.container.tsx
  package-lock.json
  package.json
  shared/components/HeaderLabelsEditor/test/HeaderLabelsEditor.test.js
  shared/contexts/Microfrontend.js
  shared/hooks/useSideDrawer.js
  shared/package-lock.json
  shared/package.json
Labels: size/XL, lgtm

#45 Bump vulnerable dependencies' versions
  compass/.env
  package-lock.json
  package.json
Labels: :wave: request review, lgtm, size/XXL
