Repository kyma-incubator/compass-console, pull requests merged in 2021-04, with the labels that each got.

#25 Fix application scenario assignment
  compass/src/components/Application/ApplicationDetails/ApplicationDetailsScenarios/ApplicationDetailsScenarios.js
  package-lock.json
Labels: :wave: request review, bug

#24 Fix asyncapi convertion
  compass/src/components/Api/ApiDetails/ApiDetails.js
  components/generic-documentation/package-lock.json
  components/generic-documentation/package.json
  components/generic-documentation/src/index.tsx
  package-lock.json
  package.json
Labels: :wave: request review

#26 Allow auth list to be null
  compass/src/components/ApiPackages/ApiPackageDetails/AuthList/AuthList.js
Labels: :wave: request review, bug

#28 Update base image
  compass/Dockerfile
Labels: :wave: request review

#27 Update dependencies
  compass/package-lock.json
  compass/package.json
  components/generic-documentation/package-lock.json
  components/generic-documentation/package.json
  components/react/package-lock.json
  components/react/package.json
  package-lock.json
  package.json
  shared/package-lock.json
  shared/package.json
Labels: :wave: request review

#30 Fix scroll on multichoice list
  compass/src/App.scss
  compass/src/components/Applications/CreateApplicationModal/CreateApplicationModal.component.js
  compass/src/components/Scenarios/CreateScenario/CreateScenarioForm/CreateScenarioForm.component.js
  compass/src/components/Scenarios/ScenarioDetails/shared/AssignEntityToScenarioModal/AssignEntityToScenarioModal.component.js
  compass/src/components/Shared/AssignScenario/AssignScenarioModal.component.js
  compass/src/components/Shared/MultiChoiceList/MultiChoiceList.component.js
Labels: :wave: request review, lgtm
