Repository kyma-incubator/compass-console, pull requests merged in 2022-01, with the labels that each got.

#52 Vulnerabilities fix
  compass/package-lock.json
  compass/package.json
  components/generic-documentation/package-lock.json
  components/generic-documentation/package.json
  package-lock.json
Labels: :wave: request review, lgtm, size/XXL

#53 Logout from IDP on logout
  compass/src/config/luigi-config/auth.js
  scripts/setClusterConfig.sh
Labels: :wave: request review, lgtm, size/S

#54 Restrict spec upload file size
  compass/src/components/Api/CreateApiForm/CreateApiForm.js
Labels: :wave: request review, lgtm, size/XS
