Repository kyma-incubator/compass-console, pull requests merged in 2022-03, with the labels that each got.

#56 Drop dex
  .clusterConfig.default
  .eslintrc.json
  .prettierignore
  README.md
  compass/Dockerfile
  compass/nginx.conf
  compass/package-lock.json
  compass/package.json
  compass/public-luigi/index.html
  compass/public-luigi/oidc/secret.js
  compass/public/index.html
  compass/public/oidc/secret.js
  compass/src/config/luigi-config/auth.js
  compass/start.sh
  components/generic-documentation/package-lock.json
  package.json
  scripts/setClusterConfig.sh
Labels: :wave: request review, size/L, lgtm

#61 Adopt stalebot with lifecycle plugin
  .github/stale.yml
Labels: lgtm, size/XS

#62 Fix misplaced loader in tenant search
  compass/src/components/TenantSearch/TenantSearch.js
  compass/src/components/TenantSearch/TenantSearch.scss
Labels: kind/bug, lgtm, size/M
